From mathcomp Require Import ssreflect ssrnat eqtype.
From deriving Require Import deriving.

Require Import type.

(* t_rect is the recursor automatically generated by Coq *)
Time Definition t_indDef n := [indDef for t_rect n].
Canonical t_indType n := Eval hnf in IndType (t n) (t_indDef n).

Time Definition t_eqMixin (n:nat) := [derive eqMixin for t n].
Canonical t_eqType (n:nat) := Eval hnf in EqType (t n) (t_eqMixin n).
