From mathcomp Require Import ssreflect ssrnat eqtype.
From deriving Require Import deriving.

Require Import type.

(* nat_indType is already defined, so to be sure that we don't rely on it,
   we redefine nat *)
Inductive nat := | O | S : nat -> nat.

(* t_rect is the recursor automatically generated by Coq *)
Time Definition nat_indDef := [indDef for nat_rect].
Canonical nat_indType := IndType nat nat_indDef.

Time Definition nat_eqMixin := [derive eqMixin for nat].
Canonical nat_eqType := EqType nat nat_eqMixin.
