From mathcomp Require Import ssreflect ssrnat eqtype.
From deriving Require Import deriving.

Require Import type.

Inductive list A := | nil | cons : A -> list A -> list A.

(* t_rect is the recursor automatically generated by Coq *)
Time Definition list_indDef A := [indDef for list_rect A].
Canonical list_indType A := IndType (list A) (list_indDef A).

Time Definition list_eqMixin (A : eqType) := [derive eqMixin for list A].
Canonical list_eqType (A:eqType) := EqType (list A) (list_eqMixin A).
