From mathcomp Require Import ssreflect ssrnat eqtype.
From deriving Require Import deriving.

Require Import type.

(* cf. https://github.com/arthuraa/deriving/blob/master/tests/tree.v *)

(* t_rect is the recursor automatically generated by Coq *)
Time Definition t_indDef A := [indDef for t_rect A].
Canonical t_indType A := Eval hnf in IndType (t A) (t_indDef A).

Time Definition t_eqMixin (A:eqType) := [derive eqMixin for t A].
Canonical t_eqType (A:eqType) := Eval hnf in EqType (t A) (t_eqMixin A).
