From mathcomp Require Import ssreflect eqtype.
From deriving Require Import deriving.

Require Import type.

(* t_rect is the recursor automatically generated by Coq *)
Time Definition t_indDef := [indDef for t_rect].
Canonical t_indType := IndType t t_indDef.

Time Definition t_eqMixin := [derive eqMixin for t].
Canonical t_eqType := EqType t t_eqMixin.
