Inductive t :=
| C0 : t
| C1 : nat -> t
| C2 : nat -> nat -> t
| C3 : nat -> nat -> nat -> t
| C4 : nat -> nat -> nat -> nat -> t
| C5 : nat -> nat -> nat -> nat -> nat -> t
| C6 : nat -> nat -> nat -> nat -> nat -> nat -> t
| C7 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C8 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C9 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C10 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C11 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C12 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C13 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C14 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C15 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C16 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C17 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C18 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C19 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C20 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C21 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C22 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C23 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C24 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C25 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C26 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C27 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C28 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C29 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C30 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C31 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C32 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C33 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C34 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C35 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C36 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C37 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C38 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C39 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C40 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C41 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C42 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C43 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C44 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C45 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C46 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C47 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C48 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C49 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C50 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C51 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C52 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C53 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C54 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C55 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C56 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C57 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C58 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C59 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C60 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C61 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C62 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C63 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C64 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C65 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C66 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C67 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C68 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C69 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C70 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C71 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C72 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C73 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C74 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C75 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C76 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C77 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C78 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C79 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C80 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C81 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C82 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C83 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C84 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C85 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C86 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C87 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C88 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C89 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C90 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C91 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C92 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C93 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C94 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C95 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C96 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C97 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C98 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
| C99 : nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> nat -> t
.
